version: "3.9"
services:
  web:
    build:
      context: "."
    environment:
      DJANGO_SETTINGS_MODULE: fingerprint_api.settings.production
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: fp
      POSTGRES_PASSWORD: fp
      SECRET_KEY: insecuredevkey
      DJANGO_DEBUG: true
      DJANGO_ALLOWED_HOSTS: "*"
    volumes:
      - ".:/project"
    depends_on:
      - database
  database:
    image: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data/"
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: fp
      POSTGRES_PASSWORD: fp
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres:
